---

- name: Ensure Node.js and npm are not installed.
  ansible.builtin.apt:
    name: 
      - nodejs
    state: absent

- name: Add NodeSource repositories for Node.js.
  ansible.builtin.apt_repository:
    repo: "{{ item }}"
    state: absent
  with_items:
    - "deb https://deb.nodesource.com/node_{{ nodejs_version }} {{ ansible_distribution_release }} main"
    - "deb-src https://deb.nodesource.com/node_{{ nodejs_version }} {{ ansible_distribution_release }} main"