- name: Verify
  hosts: all
  tasks:
  
  - name: Check nodejs version
    shell: "node --version"
    register: nodejs_current_version

  - name: Ensure nodejs is installed
    assert:
      that:
        - nodejs_current_version.rc == 0

  - name: Check serverless
    shell: "serverless --version"
    register: serverless_current_version

  - name: Ensure serverless is installed
    assert:
      that:
        - serverless_current_version.rc == 0